from __future__ import annotations

import math

from pixelforge.engine.types import (
    ContourPath,
    GCodeConfig,
    GCodeStats,
    ProgressCallback,
)


def generate_gcode_2d(
    contours: list[ContourPath],
    config: GCodeConfig,
    progress_callback: ProgressCallback = None,
) -> tuple[str, GCodeStats]:
    stats = GCodeStats()
    stats.contour_count = len(contours)
    out: list[str] = []

    out.append("; =============================================")
    out.append("; CNC Engraving -- 2D Contour / Line Art")
    out.append("; Generated by PixelForge CNC v4.1.0")
    out.append(f"; Material: {config.material}")
    out.append(f"; Output: {config.width_mm}mm x {config.height_mm}mm")
    out.append(f"; Contours: {len(contours)}")
    out.append(f"; Passes: {config.contour_passes}")
    out.append(f"; Feed: {config.feed_rate}mm/min | RPM: {config.spindle_rpm}")
    out.append("; =============================================")
    out.append("")
    out.append("T1 M6")
    out.append("G17")
    out.append("G21")
    out.append("G90")
    out.append(f"G0 Z{config.safe_z:.3f}")
    out.append(f"G0 X0.000 Y0.000 S{config.spindle_rpm} M3")
    out.append("G4 P2")
    out.append("")
    stats.rapid_moves += 2

    if progress_callback:
        progress_callback(0.0, f"Generating {len(contours)} contour paths...")

    sorted_contours = sorted(
        contours,
        key=lambda c: _contour_bounds(c),
    )

    total_paths = len(sorted_contours) * config.contour_passes
    path_idx = 0

    lead_len = 0.5
    lead_feed = config.plunge_rate * 0.5

    for pass_num in range(config.contour_passes):
        depth_fraction = (pass_num + 1) / max(config.contour_passes, 1)
        current_depth = config.max_depth * depth_fraction

        for contour in sorted_contours:
            if len(contour.points) < 2:
                continue

            path_idx += 1
            if progress_callback and path_idx % 5 == 0:
                progress_callback(
                    path_idx / max(total_paths, 1),
                    f"Cutting path {path_idx}/{total_paths}",
                )

            mm_points = contour.points
            first_x, first_y = mm_points[0]
            dx0 = mm_points[1][0] - mm_points[0][0] if len(mm_points) > 1 else 0
            dy0 = mm_points[1][1] - mm_points[0][1] if len(mm_points) > 1 else 0
            ln = math.hypot(dx0, dy0)
            if ln > 1e-6:
                lead_x = first_x + (dx0 / ln) * lead_len
                lead_y = first_y + (dy0 / ln) * lead_len
            else:
                lead_x, lead_y = first_x, first_y

            out.append(f"G0 Z{config.safe_z:.3f}")
            out.append(f"G0 X{lead_x:.3f} Y{lead_y:.3f}")
            out.append(f"G0 Z{config.start_z:.3f}")
            stats.rapid_moves += 3

            out.append(f"G1 Z{current_depth:.3f} F{config.plunge_rate:.0f}")
            stats.cutting_moves += 1

            out.append(f"G1 X{first_x:.3f} Y{first_y:.3f} F{lead_feed:.0f}")
            stats.cutting_moves += 1

            for i, (px, py) in enumerate(mm_points):
                if i == 0:
                    continue
                out.append(f"G1 X{px:.3f} Y{py:.3f}")
                stats.cutting_moves += 1

            if contour.is_closed and len(mm_points) > 2:
                out.append(f"G1 X{first_x:.3f} Y{first_y:.3f}")
                stats.cutting_moves += 1

            out.append(f"G0 Z{config.safe_z:.3f}")
            stats.rapid_moves += 1

            dist = 0.0
            for i in range(1, len(mm_points)):
                dx = mm_points[i][0] - mm_points[i - 1][0]
                dy = mm_points[i][1] - mm_points[i - 1][1]
                dist += math.sqrt(dx * dx + dy * dy)
            stats.cutting_distance_mm += dist

    out.append("")
    out.append(f"G0 Z{config.safe_z:.3f}")
    out.append("G0 X0.000 Y0.000")
    out.append("M5")
    out.append("M30")
    stats.rapid_moves += 2
    stats.total_lines = len(out)

    if config.feed_rate > 0:
        stats.estimated_time_seconds = (
            stats.cutting_distance_mm / config.feed_rate * 60.0
        )

    if progress_callback:
        progress_callback(1.0, f"G-code complete: {stats.total_lines} lines")

    return "\n".join(out), stats


def _contour_bounds(c: ContourPath) -> tuple[float, float]:
    if not c.points:
        return (0.0, 0.0)
    xs = [p[0] for p in c.points]
    ys = [p[1] for p in c.points]
    return (min(xs) + max(xs)) / 2.0, (min(ys) + max(ys)) / 2.0
